#!/usr/bin/env bash
#checking if file school exists

file="touch school"

if [ -e "$file" ]; then
  echo "school file exists"
     if [ -s "$file" ]; then
        echo "school file is empty"
     else
        echo "school file is not empty"
     fi
     if [ -f "$file" ]; then
        echo "school is a regular file"
     else
        echo "(nothing)"
     fi
else
  echo "school file does not exist"
fi
