#!/usr/bin/env bash
#managing the process

#!/bin/bash

PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"

start_process() {
    ./$PROCESS_NAME &
    echo $! > $PID_FILE
    echo "$PROCESS_NAME started"
}

stop_process() {
    if [ -f "$PID_FILE" ]; then
        kill "$(cat $PID_FILE)"
        rm -f "$PID_FILE"
        echo "$PROCESS_NAME stopped"
    else
        echo "No PID file found. Is the process running?"
    fi
}

restart_process() {
    stop_process
    start_process
    echo "$PROCESS_NAME restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

